# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('CourseId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('CreateDate', models.DateTimeField(default=datetime.datetime(2017, 6, 13, 21, 45, 41, 937680, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='EditTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('CreateDate', models.DateTimeField(default=datetime.datetime(2017, 6, 13, 21, 45, 41, 958194, tzinfo=utc))),
                ('state', models.CharField(max_length=100)),
                ('AudioExtractDate', models.DateTimeField(null=True)),
                ('STTDate', models.DateTimeField(null=True)),
                ('SegmentDate', models.DateTimeField(null=True)),
                ('note', models.TextField(null=True)),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
