# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 00:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edittask',
            old_name='note',
            new_name='TaskNote',
        ),
        migrations.RenameField(
            model_name='edittask',
            old_name='state',
            new_name='TaskState',
        ),
        migrations.RenameField(
            model_name='edittask',
            old_name='type',
            new_name='TaskType',
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 0, 0, 13, 214630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 0, 0, 13, 235144, tzinfo=utc)),
        ),
    ]
