# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 02:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170614_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='SegmentTime',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 2, 35, 56, 321215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 2, 35, 56, 336840, tzinfo=utc)),
        ),
    ]
