# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 05:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170616_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edittask',
            old_name='STTDate',
            new_name='FinishedDate',
        ),
        migrations.RemoveField(
            model_name='edittask',
            name='SegmentDate',
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 5, 52, 54, 33004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 5, 52, 54, 307581, tzinfo=utc)),
        ),
    ]
