# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170620_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='AbstractTextFile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='FullTextFile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='SubRipTextFile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 3, 8, 51, 267038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 3, 8, 51, 563915, tzinfo=utc)),
        ),
    ]
