# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 01:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170824_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalCategory',
            fields=[
                ('InternalCategoryId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ParentId', models.CharField(max_length=100, null=True)),
                ('path', models.CharField(max_length=1024, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lecturer',
            fields=[
                ('LecturerId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=2048, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublishCategory',
            fields=[
                ('PublishCategoryId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='AbstractTextFile',
        ),
        migrations.RemoveField(
            model_name='course',
            name='FullTextFile',
        ),
        migrations.RemoveField(
            model_name='course',
            name='SubRipTextFile',
        ),
        migrations.AddField(
            model_name='course',
            name='AbstractText',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='KeyWords',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='progress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 1, 58, 35, 763405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 1, 58, 35, 779032, tzinfo=utc)),
        ),
    ]
