# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 02:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171122_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='InternalCategory',
            field=models.ManyToManyField(null=True, to='app.InternalCategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='PublishCategory',
            field=models.ManyToManyField(null=True, to='app.PublishCategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lecturer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 2, 2, 17, 140343, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 2, 2, 17, 187225, tzinfo=utc)),
        ),
    ]
