# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 02:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171122_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 2, 5, 37, 967677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 2, 5, 37, 967677, tzinfo=utc)),
        ),
    ]
