# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 02:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20171122_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 11, 22, 2, 57, 15, 830606, tzinfo=utc))),
                ('note', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 2, 57, 15, 830606, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='InternalCategory',
            field=models.ManyToManyField(to='app.InternalCategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='PublishCategory',
            field=models.ManyToManyField(to='app.PublishCategory'),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 2, 57, 15, 846230, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='courselog',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddField(
            model_name='courselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
