# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171122_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='post',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 7, 4, 56, 730806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 7, 4, 56, 732307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 7, 4, 56, 733808, tzinfo=utc)),
        ),
    ]
