# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171122_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='PhotoSrc',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 5, 21, 39, 22283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 5, 21, 39, 22283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 5, 21, 39, 22283, tzinfo=utc)),
        ),
    ]
