# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171206_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='EpisodeCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 6, 56, 53, 658414, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 6, 56, 53, 674040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 6, 56, 53, 674040, tzinfo=utc)),
        ),
    ]
