# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 02:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20171214_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 2, 38, 49, 318811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 2, 38, 49, 334424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 2, 38, 49, 334424, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='courseabstract',
            unique_together=set([('course', 'index')]),
        ),
        migrations.AlterIndexTogether(
            name='courseabstract',
            index_together=set([]),
        ),
    ]
