# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 00:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20171214_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='GroupName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 0, 21, 48, 102627, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 0, 21, 48, 104628, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 0, 21, 48, 106629, tzinfo=utc)),
        ),
    ]
