# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 04:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20171221_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='PublishCategory',
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 4, 57, 46, 737445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 4, 57, 46, 738946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 4, 57, 46, 740947, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='PublishCategory',
        ),
    ]
