# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 04:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20171222_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishCategory',
            fields=[
                ('PublishCategoryId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 4, 58, 18, 414369, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 4, 58, 18, 415870, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 4, 58, 18, 417871, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='course',
            name='PublishCategory',
            field=models.ManyToManyField(to='app.PublishCategory'),
        ),
    ]
