# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20180118_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('FilePath', models.CharField(max_length=1024)),
                ('note', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('CustomerId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('PassWord', models.CharField(max_length=100)),
                ('CustomerName', models.CharField(max_length=100)),
                ('sort', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 2, 56, 14, 875647, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 2, 56, 14, 875647, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='coursetemplet',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
