# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 03:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20180222_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesource',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='state',
        ),
        migrations.AddField(
            model_name='edittask',
            name='TaskPriority',
            field=models.CharField(default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 3, 14, 40, 584503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 3, 14, 40, 584503, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='edittask',
            name='course',
        ),
        migrations.AddField(
            model_name='edittask',
            name='course',
            field=models.ManyToManyField(null=True, to='app.course'),
        ),
        migrations.DeleteModel(
            name='CourseSource',
        ),
    ]
