# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 03:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20180419_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 3, 15, 35, 38134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 3, 15, 35, 38134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='course',
            field=models.ManyToManyField(to='app.course'),
        ),
    ]
