# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 05:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20180419_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='TempletType',
            field=models.CharField(default='slide', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 5, 47, 11, 873547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 5, 47, 11, 873547, tzinfo=utc)),
        ),
    ]
