# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20180425_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalcategory',
            name='ParentId',
        ),
        migrations.AddField(
            model_name='internalcategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.InternalCategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 2, 40, 25, 380778, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 2, 40, 25, 380778, tzinfo=utc)),
        ),
    ]
