# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20180508_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 2, 51, 42, 685695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 2, 51, 42, 685695, tzinfo=utc)),
        ),
    ]
