# Generated by Django 2.0.7 on 2018-09-30 00:01

import datetime
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_pgjsonb.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20180720_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='MakeDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitles',
            field=django_pgjsonb.fields.JSONField(decode_kwargs={}, encode_kwargs={'cls': django.core.serializers.json.DjangoJSONEncoder}, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 0, 1, 57, 131815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='ExtendedData',
            field=django_pgjsonb.fields.JSONField(decode_kwargs={}, encode_kwargs={'cls': django.core.serializers.json.DjangoJSONEncoder}, null=True),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 0, 1, 57, 133813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='log',
            field=django_pgjsonb.fields.JSONField(decode_kwargs={}, encode_kwargs={'cls': django.core.serializers.json.DjangoJSONEncoder}, null=True),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
