# Generated by Django 2.0.7 on 2018-11-01 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20180930_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetemplet',
            name='customer',
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 4, 47, 48, 81919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 4, 47, 48, 81919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='edittask',
            name='ExtendedData',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
