# Generated by Django 2.1.1 on 2019-01-21 05:20

import datetime
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_pgjsonb.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0039_auto_20181105_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReEditCourse',
            fields=[
                ('CourseId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('GroupName', models.CharField(max_length=200, null=True)),
                ('CreateDate', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 5, 20, 41, 682875, tzinfo=utc))),
                ('MakeDate', models.DateTimeField(null=True)),
                ('ProjectId', models.CharField(max_length=100, null=True)),
                ('FilePath', models.CharField(max_length=1024, null=True)),
                ('SlideVersion', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('TempletType', models.CharField(default='slide', max_length=100)),
                ('duration', models.IntegerField(null=True)),
                ('EpisodeCount', models.IntegerField(null=True)),
                ('progress', models.CharField(max_length=100, null=True)),
                ('KeyWords', models.CharField(max_length=1024, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('ExtendedData', django_pgjsonb.fields.JSONField(decode_kwargs={}, encode_kwargs={'cls': django.core.serializers.json.DjangoJSONEncoder}, null=True)),
                ('subtitles', django_pgjsonb.fields.JSONField(decode_kwargs={}, encode_kwargs={'cls': django.core.serializers.json.DjangoJSONEncoder}, null=True)),
                ('InternalCategory', models.ManyToManyField(to='app.InternalCategory')),
                ('PublishCategory', models.ManyToManyField(to='app.PublishCategory')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 5, 20, 41, 679948, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 5, 20, 41, 685809, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='reeditcourse',
            name='SourceCourseId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddField(
            model_name='reeditcourse',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reeditcourse',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lecturer'),
        ),
    ]
